### ISSUE TITLE
Cleanup Images Plugin reads images being used in Snowball as unattached and deletes them

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#157]
- The Cleanup Images plugin deletes unused images from a WP Library.
- If an image is added to a Snowball Article it should be tagged as attached and not be deleted by Cleanup Images but that doesn't happen. On Cleanup it doesn't read images being used in SNowball and deletes them.

**Comment by sukritchhabra** [comment]
- #139

**Comment by thomaspark** [comment]
Plugin might no longer be supported (wasn't able to find a link), but we should still make sure uploaded images get attached to post.

**Comment by sukritchhabra** [comment]
- Just tested on test.opengtml, and images are getting attached. 
- It recognizes that images were attached, do not know if it recognizes which article they're attached to.
- WP also doesn't understand that they are unattached if they were attached at some point and then removed.
- it shows the option to filter by 'Uploaded to this post' only sometimes

**Comment by thomaspark** [comment]
Seems that images are getting attached to posts properly.

For your point 3, even if the images are unused, they remain attached to the post they were originally uploaded to, so this is the expected behavior.

We should try to replicate point 4. If we're able to do that, let's open it as its own issue.
