### ISSUE TITLE
Support Advanced Art Direction plugin in Snowball admin

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#206]

**Comment by noelforte** [comment]
Make an edit to this— I got the plugin name wrong. It's "Better Art Direction" https://github.com/davatron5000/Better-Art-Direction. See the screenshot below for what it provides as UI.

<img width="700" alt="screen shot 2015-10-13 at 11 23 34 pm" src="https://cloud.githubusercontent.com/assets/2560683/10474178/76dd5a6a-7201-11e5-98ea-5aa8a5f0c325.PNG">

Essentially, it just loads a 2 pane textarea panel into the post editor so you can add styles and scripts that are specific to that page. Really useful for injecting custom styles onto a page to modify a layout, but with Snowball having a UI is way better. Still, one reason I'd like to use this plugin is because it allows us to load in external scripts or stylesheets in the page `<head>`. If a feature like this could be implemented in Snowball, that would make things simpler as The Triangle wouldn't have to depend on 2 plugins to make this work.

**Comment by thomaspark** [comment]
I've added a similar option to add your own styles and scripts in the head of an article. This will apply to the entire page, not just a single block.

<img width="807" alt="screen shot 2015-11-03 at 12 53 26 am" src="https://cloud.githubusercontent.com/assets/900407/10921686/ed877e9a-8244-11e5-9897-b60c76300cd0.png">

**Comment by noelforte** [comment]
This looks awesome! :+1: When will this be released?

**Comment by thomaspark** [comment]
We just went live on WordPress.org an hour ago! https://wordpress.org/plugins/snowball/

You should be able to just hit update in WP admin plugins.
