### ISSUE TITLE
HTML/CSS not editable

### ISSUE THREAD

**Issue by noelforte** [thomaspark/snowball#211]
Is it possible to edit the HTML/CSS of snowball modules? The code button shows the HTML/CSS, and I can put my cursor in their boxes, but I can't seem to edit anything.

**Comment by thomaspark** [comment]
The default CSS is read only, but you can override it by scrolling down to the bottom with a darker background and adding your own:

<img width="662" alt="screen shot 2015-11-03 at 8 59 54 pm" src="https://cloud.githubusercontent.com/assets/900407/10927446/df490848-826d-11e5-8b86-1ad15572cd90.png">

We don't want to allow editing the HTML because it could change (i.e. break) the fundamentals of the block. If you do want to write your own HTML, we recommend you use the HTML module, which is open ended:

<img width="1321" alt="screen shot 2015-11-03 at 9 01 10 pm" src="https://cloud.githubusercontent.com/assets/900407/10927488/0c95f072-826e-11e5-94be-cb8dee6b610e.png">

**Comment by noelforte** [comment]
Excellent.
