### ISSUE TITLE
Snowball Articles Not Appearing in Feeds or Front Page

### ISSUE THREAD

**Issue by PeachParser** [thomaspark/snowball#223]
Amazing plugin, but I've noticed that Snowball articles don't display correctly (or at all) in some themes. I'm currently testing in the popular [Newspaper 6](http://themeforest.net/item/newspaper/5489609). Snowball articles appear in search results, but nowhere else, including the front page, other feeds, etc. Snowball articles also are not listed in the Wordpress "Posts" list, though I figure that might be intentional owing to being a custom content type.

Let me know if I can provide additional info to help reproduce the issue. Happy to help troubleshoot on this end too if you have any leads.

**Comment by thomaspark** [comment]
Hey @PeachParser, thanks for reporting the issue. We've tested on popular themes like Twenty Fifteen, and Snowball articles do display on the front page when it's set to show latest posts. It should work similarly with Newspaper 6, but we unfortunately have no way of testing since it's a premium theme.

Can you try testing Twenty Fifteen on your end to make sure it's working as expected.
