### ISSUE TITLE
synchronous xmlhttprequest on main thread warning

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#25]
```
load-scripts.php:4
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects
to the end user's experience.
```

**Comment by brianlee389** [comment]
This seems to come out whenever an snowball.addBlock button is clicked, why I can't figure it out why at the moment.

**Comment by brianlee389** [comment]
http://stackoverflow.com/questions/24740773/synchronous-xmlhttprequest-on-the-main-thread-is-deprecated
I found out this error is caused by appending a script tag to a dom.
Which is done in the function renderPreview.
I couldn't find a fix for it, but I haven't found that it does anything bad except make that message appear.

**Comment by thomaspark** [comment]
I initially thought that appending the script tag in `renderPreview()` was causing the warning, but it seems to be a native WordPress issue. I tested this by disabling all plugins and the warning still occurred.
