### ISSUE TITLE
Parallax only works on some browsers

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#65]
Safari and Chrome on the mac doesn't work.
On windows, Chrome parallax works but the text is shifted to the left and IE parallax works, but pseudo selectors don't work.

**Comment by sukritchhabra** [comment]
I tried it again and in chrome(on windows) also, the pseudo selectors for the quote are getting affected. But this time the text remained centered.

**Comment by thomaspark** [comment]
I think all of this is caused by the `jquery.scoped.js` polyfill, which is buggy. It works on Firefox because the polyfill isn't used since it already supports `<style scoped>`. It's likely that other modules/properties are being affected by the polyfill as well.

I'm going to disable the polyfill for now. This should fix parallax, but will cause other issues (for example, all splash blocks get their background image overridden to the same one).

We may need to write our own polyfill to address #47. :sweat:
