### ISSUE TITLE
404 if WordPress permalink setting is not "Post name"

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#71]

**Comment by brianlee389** [comment]
WordPress database error: [Duplicate key name 'ID']
ALTER TABLE wp_snowball_blocks ADD UNIQUE KEY ID (id)

WordPress database error: [Duplicate key name 'ID']
ALTER TABLE wp_snowball_articles ADD UNIQUE KEY ID (id)

Here's the error from the log that was created.
http://wordpress.stackexchange.com/questions/3533/the-plugin-generated-80-characters-of-unexpected-output

**Comment by brianlee389** [comment]
I found out this was a database script issue that happens in the installation.
The error was:
WordPress database error: [Duplicate key name 'ID']
ALTER TABLE wp_snowball_blocks ADD UNIQUE KEY ID (id)

WordPress database error: [Duplicate key name 'ID']
ALTER TABLE wp_snowball_articles ADD UNIQUE KEY ID (id)

I was using unique key improperly and I instead used Primary Key because ID seems sufficient enough to determine it's uniqueness.

**Comment by brianlee389** [comment]
I used this site to help me figure it out.

**Comment by thomaspark** [comment]
Is this meant to be for #66 or is it also related to this issue?

**Comment by brianlee389** [comment]
My fix was meant for #66. My bad.

**Comment by brianlee389** [comment]
Is there more descriptions about this error?

**Comment by thomaspark** [comment]
When this setting was changed from "Post name", I thought the snowball articles were 404ing. But I was mistaken, everything seems to be working.

![screen shot 2015-06-24 at 11 05 08 am](https://cloud.githubusercontent.com/assets/900407/8333462/f90f3c18-1a60-11e5-80c3-4ed8a481bb8f.png)
