### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#91]
refreshEditors() be called only when code view is selected.

**Comment by brianlee389** [comment]
renderPreview() shouldn't be called when pressing arrow keys in editor.

**Comment by brianlee389** [comment]
Using a css and javascript minifier whenever we run the plugin.
http://blog.fusioncharts.com/2014/06/5-excellent-javascript-minification-tools-to-improve-your-code-performance/
Using Grunt with Worpress
http://code.tutsplus.com/tutorials/using-grunt-with-wordpress-development--cms-21743

**Comment by brianlee389** [comment]
Some links on ways to improve efficiency:
http://www.smashingmagazine.com/2014/06/25/how-to-speed-up-your-wordpress-website/
http://www.wpbeginner.com/wp-tutorials/9-most-useful-htaccess-tricks-for-wordpress/

**Comment by thomaspark** [comment]
For future reference, right now our script load and execution for 7 blocks takes about 1.7 seconds. This is for default blocks of map, quote, image, splash, table, text, video. Here's a breakdown:

![screen shot 2015-06-27 at 12 50 03 pm](https://cloud.githubusercontent.com/assets/900407/8393012/106b8468-1ccb-11e5-9d7d-24e406edd5bb.png)

Here's an overview of all blocks:

![screen shot 2015-06-27 at 12 54 09 pm](https://cloud.githubusercontent.com/assets/900407/8393031/c69599e0-1ccb-11e5-8d3e-1244e340ea33.png)

Each addBlock takes from 120m (quote block) to 260ms (for table block). Here's a close look at one of those blocks:

![screen shot 2015-06-27 at 12 55 00 pm](https://cloud.githubusercontent.com/assets/900407/8393030/bc4f0944-1ccb-11e5-96c2-809575728ea9.png)

**Comment by thomaspark** [comment]
Made a few optimizations.

**Delay codemirror initialization (add16abcf42784e0ae6a7fe9fd48322ba6201d0d) - 1.27s (25%)**
Instead of initializing all code editors on load, we wait until the user clicks the zoom button for a particular block, checks if codemirror exists for that block, and then initialize if it doesn't exist.

**Initialize codemirror on zoom mouseover instead of click (999406d9b3b3ed8ce818d2ee389ca54b78aa4f5f) - no change**
There was a slight delay while codemirror initialized when a user clicked the zoom button for a block. Moving the init check to hover instead of click doesn't get rid of the delay, but it's no longer perceptible to the user.

**Remove unneeded refreshEditors and renderPreview in addBlock (999406d9b3b3ed8ce818d2ee389ca54b78aa4f5f) - 1.03s (19%)**
refreshEditors is no longer needed since we wait to initialize code editors. There were also two renderPreview — one at the end of addBlock, and another in `snowball-preview` iframe's load handler, which gets fired when the preview iframe gets added to the DOM. This was because the load event didn't seem to be firing for Safari (it was in fact firing, but also setting transform scale to 0 for some blocks). This has been fixed, so one of the renderPreviews can be dropped.

**Use id instead of class (1d1c9e789343ef6e305b155f1c327848f1106f17) - a few milliseconds**
Changed `#snowball-toolbar` and `#snowball-main` from class to ID. Since there will only ever be one of each, we can use ID for our selectors, which is more efficient since it stops after finding one.

Load time is down from 1.70s to 960ms.

![screen shot 2015-06-28 at 11 01 05 am](https://cloud.githubusercontent.com/assets/900407/8396848/cc3a443a-1d85-11e5-8df9-dd34e45b3036.png)

**Comment by thomaspark** [comment]
Closing this. We can open new issues for any specific performance bottlenecks we identify.
